# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dfc15feb97a13149be249325d8a015145e107aa5ddab98ea592c6afa41e64648a99f2e62d55d57dd904c59e295a4b9b467049042401c6e124f48f8f99ecd93e6

test:
  secret_key_base: 2b526b2a67026e38ec9217da92012187596d1dad022034c7ed99bda2df0b7a34a1dcba743bb5b97c32e9da3d0b7faef138237a912d5f1e8713851567f10eb265

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
